# Generated by Django 3.2.6 on 2021-11-08 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudioRadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageCourant_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Resistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=45)),
                ('studioRadio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.studioradio')),
            ],
        ),
    ]
