# Generated by Django 3.2.6 on 2021-11-08 14:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 8, 14, 2, 11, 200983))),
            ],
        ),
        migrations.CreateModel(
            name='Resistant_has_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Resistant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.resistant')),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.message')),
            ],
        ),
    ]
