# Generated by Django 3.2.6 on 2021-11-08 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_message_resistant_has_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.date(2021, 11, 8)),
        ),
    ]
