# Generated by Django 3.2.6 on 2021-11-08 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0006_alter_message_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosteRadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageCourant_text', models.CharField(max_length=255)),
                ('StudioRadio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.studioradio')),
            ],
        ),
    ]
