# Generated by Django 3.2.6 on 2021-11-08 16:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0007_posteradio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resistant_has_message',
            name='Resistant_id',
        ),
        migrations.AddField(
            model_name='resistant_has_message',
            name='action_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.date, null=True),
        ),
        migrations.AlterField(
            model_name='posteradio',
            name='StudioRadio_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='radio.studioradio'),
        ),
        migrations.AlterField(
            model_name='posteradio',
            name='messageCourant_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='resistant',
            name='pseudo',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='resistant_has_message',
            name='message_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='radio.message'),
        ),
        migrations.AlterField(
            model_name='studioradio',
            name='messageCourant_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='GroupeClandestin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=45)),
                ('messageAttendu_text', models.CharField(blank=True, max_length=255)),
                ('PosteRadio_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='radio.posteradio')),
            ],
        ),
        migrations.CreateModel(
            name='Envahisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(blank=True, max_length=45)),
                ('PosteRadio_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='radio.posteradio')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(blank=True, max_length=45)),
                ('message_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='radio.message')),
            ],
        ),
    ]
