# Generated by Django 3.2.6 on 2021-11-09 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0008_auto_20211108_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='message_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='radio.message'),
        ),
    ]
