# Generated by Django 3.2.6 on 2021-11-09 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0011_alter_envahisseur_posteradio_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resistant_has_message',
            name='message_id',
        ),
        migrations.AlterField(
            model_name='resistant',
            name='studioRadio',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='radio.studioradio'),
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='Resistant_has_message',
        ),
    ]
