# Generated by Django 3.2.6 on 2021-11-09 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0012_auto_20211109_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resistant_has_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='radio.message')),
                ('resistant_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='radio.resistant')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_text', models.CharField(blank=True, max_length=45)),
                ('message_id', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='radio.message')),
            ],
        ),
    ]
