# Generated by Django 3.2.6 on 2021-11-22 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0014_auto_20211122_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlotteAllie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=25)),
                ('resistant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.resistant')),
            ],
        ),
    ]
